name: Manual Run
on:
  workflow_dispatch:
    inputs:
      cmdline:
        description: Shell Command for private action
        required: true
        default: pwd
      arg0:
        required: false
        default: ''
      arg1:
        required: false
        default: ''
jobs:
  execute_cmdline_job:
    runs-on: ubuntu-latest
    name: A job to run private action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List homedir before
        run: |
          echo "*** Hello! ***"
          pwd
          ls -la
          ls -la /home/runner/work

      - name: Run private action
        uses: ./.github/actions/gh-act1/
        id: run_priv_action
        with:
          cmdline: ${{ github.event.inputs.cmdline }}
          arg0: ${{ github.event.inputs.arg0 }}
          arg1: ${{ github.event.inputs.arg1 }}

      - name: List homedir after
        if: always()
        run: |
          echo "*** Hello! ***"
          pwd
          ls -la
          ls -la /home/runner/work
